//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QA29v55Entities : DbContext
    {
        public QA29v55Entities()
            : base("name=QA29v55Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EntityProperty> EntityProperties { get; set; }
    
        public virtual int GetEntityProperties(string entityTypeID)
        {
            var entityTypeIDParameter = entityTypeID != null ?
                new ObjectParameter("EntityTypeID", entityTypeID) :
                new ObjectParameter("EntityTypeID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetEntityProperties", entityTypeIDParameter);
        }
    }
}
