using System;
using EntityModel.Models;

namespace EntityModel.UnitTests
{
    public class OwnSiteProperties
    {
        public static EntityPropertyCollection Get()
        {
            var propertyCollection = new EntityPropertyCollection
            {
                TableName = "OwnSite",
            };

            propertyCollection.Properties = new EntityProperty[]
            {
                new EntityProperty                {                    Id = 531,                    Name = "AreaUID",                    DisplayOrder = 40,                    Required = true,                    TxId = 40,                    Value = new Guid("38173EF8-8359-434E-A096-4C937C4F9CEA")                },
                new EntityProperty                {                    Id = 568,                    Name = "NetworkUID",                    DisplayOrder = 50,                    Required = true,                    TxId = 50,                    Value = new Guid("6A5FE10C-B433-4724-8524-E6994ADDFF18")                },
                new EntityProperty                {                    Id = 554,                    Name = "ImportCode",                    DisplayOrder = 20,                    Required = true,                    TxId = 20,                 Value = "K999"                },
                new EntityProperty                {                    Id = 567,                    Name = "Name",                    DisplayOrder = 10,                    Required = true,                    TxId = 10,                 Value = "NewOwnSite"                },
                new EntityProperty                {                    Id = 525,                    Name = "Address",                    DisplayOrder = 55,                    Required = false,                    TxId = 55,                 Value = "1191 S BUCKLEY RD / E ARIZONA DR"                },
                new EntityProperty                {                    Id = 526,                    Name = "Address2",                    DisplayOrder = 56,                    Required = false,                    TxId = 56,                },
                new EntityProperty                {                    Id = 527,                    Name = "Address3",                    DisplayOrder = 57,                    Required = false,                    TxId = 57,                },
                new EntityProperty                {                    Id = 528,                    Name = "Address4",                    DisplayOrder = 58,                    Required = false,                    TxId = 58,                },
                new EntityProperty                {                    Id = 529,                    Name = "Address5",                    DisplayOrder = 59,                    Required = false,                    TxId = 59,                },
                new EntityProperty                {                    Id = 573,                    Name = "PostCode",                    DisplayOrder = 60,                    Required = false,                    TxId = 60,                },
                new EntityProperty                {                    Id = 537,                    Name = "Country",                    DisplayOrder = 61,                    Required = false,                    TxId = 61,                },
                new EntityProperty                {                    Id = 591,                    Name = "TimeZoneID",                    DisplayOrder = 62,                    Required = true,                    TxId = 62,                    Value = 36                },
                new EntityProperty                {                    Id = 561,                    Name = "ManagerName",                    DisplayOrder = 63,                    Required = false,                    TxId = 63,                 Value = "Anthony Thompson"                },
                new EntityProperty                {                    Id = 562,                    Name = "ManagerPhone",                    DisplayOrder = 64,                    Required = false,                    TxId = 64,                },
                new EntityProperty                {                    Id = 559,                    Name = "ManagerEmail",                    DisplayOrder = 65,                    Required = false,                    TxId = 65,                 Value = ""                },
                new EntityProperty                {                    Id = 560,                    Name = "ManagerFax",                    DisplayOrder = 66,                    Required = false,                    TxId = 66,                },
                new EntityProperty                {                    Id = 563,                    Name = "ManagerSMS",                    DisplayOrder = 67,                    Required = false,                    TxId = 67,                },
                new EntityProperty                {                    Id = 564,                    Name = "ManagerUserUID",                    DisplayOrder = 68,                    Required = false,                    TxId = 68,                },
                new EntityProperty                {                    Id = 577,                    Name = "PriorityUID",                    DisplayOrder = 54,                    Required = true,                    TxId = 54,                    Value = new Guid("0FDAE974-229F-4F21-A607-EB2E633D1522")                },
                new EntityProperty                {                    Id = 594,                    Name = "UserUID",                    DisplayOrder = 80,                    Required = false,                    TxId = 80,                },
                new EntityProperty                {                    Id = 534,                    Name = "BrandUID",                    DisplayOrder = 51,                    Required = true,                    TxId = 51,                    Value = new Guid("EF19D207-B3C6-43E7-AD4C-72686AAFD16B")                },
                new EntityProperty                {                    Id = 589,                    Name = "TerminalUID",                    DisplayOrder = 53,                    Required = true,                    TxId = 53,                    Value = new Guid("4C9DE53D-C594-4E70-8C92-2BDD2638563B")                },
                new EntityProperty                {                    Id = 535,                    Name = "ChannelOfTradeUID",                    DisplayOrder = 52,                    Required = true,                    TxId = 52,                    Value = new Guid("15541EF2-63EF-4954-9F1A-13554ED486E6")                },
                new EntityProperty                {                    Id = 582,                    Name = "SFROnPGFail",                    DisplayOrder = 0,                    Required = false,                    TxId = 0,                    Value = false                },
                new EntityProperty                {                    Id = 592,                    Name = "UseEmail",                    DisplayOrder = 20,                    Required = false,                    TxId = 20,                    Value = false                },
                new EntityProperty                {                    Id = 593,                    Name = "UseFax",                    DisplayOrder = 40,                    Required = false,                    TxId = 40,                    Value = false                },
                new EntityProperty                {                    Id = 595,                    Name = "UseSMS",                    DisplayOrder = 60,                    Required = false,                    TxId = 60,                    Value = false                },
                new EntityProperty                {                    Id = 578,                    Name = "ProposedIsImplemented",                    DisplayOrder = 200,                    Required = true,                    TxId = 200,                    Value = false                },
                new EntityProperty                {                    Id = 545,                    Name = "ExportSubject",                    DisplayOrder = 10,                    Required = false,                    TxId = 10,                },
                new EntityProperty                {                    Id = 546,                    Name = "FormatTemplateEmailUID",                    DisplayOrder = 30,                    Required = false,                    TxId = 30,                },
                new EntityProperty                {                    Id = 547,                    Name = "FormatTemplateFaxUID",                    DisplayOrder = 50,                    Required = false,                    TxId = 50,                },
                new EntityProperty                {                    Id = 548,                    Name = "FormatTemplateSMSUID",                    DisplayOrder = 70,                    Required = false,                    TxId = 70,                },
                new EntityProperty                {                    Id = 549,                    Name = "FutureEffectiveTime",                    DisplayOrder = 10,                    Required = false,                    TxId = 10,                },
                new EntityProperty                {                    Id = 536,                    Name = "ContractTypeUID",                    DisplayOrder = 10,                    Required = true,                    TxId = 10,                    Value = new Guid("00000000-0000-0002-0001-000000000000")                },
                new EntityProperty                {                    Id = 581,                    Name = "RunningRateDays",                    DisplayOrder = 130,                    Required = true,                    TxId = 130,                    Value = 0                },
                new EntityProperty                {                    Id = 590,                    Name = "TimeWeightedCostDays",                    DisplayOrder = 140,                    Required = true,                    TxId = 140,                    Value = 0                },
                new EntityProperty                {                    Id = 555,                    Name = "Latitude",                    DisplayOrder = 501,                    Required = false,                    TxId = 501,                    Value = 39.56m                },
                new EntityProperty                {                    Id = 558,                    Name = "Longitude",                    DisplayOrder = 502,                    Required = false,                    TxId = 502,                    Value = -104.78m                },
                new EntityProperty                {                    Id = 557,                    Name = "ListPriceCompetitorUID",                    DisplayOrder = 1,                    Required = false,                    TxId = 1,                },
                new EntityProperty                {                    Id = 571,                    Name = "PHHSiteCode",                    DisplayOrder = 300,                    Required = false,                    TxId = 300,                },
                new EntityProperty                {                    Id = 580,                    Name = "RegionalManagerName",                    DisplayOrder = 67,                    Required = false,                    TxId = 67,                },
                new EntityProperty                {                    Id = 552,                    Name = "GPCGroup",                    DisplayOrder = 90,                    Required = false,                    TxId = 90,                },
                new EntityProperty                {                    Id = 570,                    Name = "OwnPriceTriggersPG",                    DisplayOrder = 50,                    Required = true,                    TxId = 50,                    Value = false                },
                new EntityProperty                {                    Id = 806,                    Name = "TriggerCompetingOwnSitePG",                    DisplayOrder = 50,                    Required = true,                    TxId = 50,                    Value = false                },
                new EntityProperty                {                    Id = 550,                    Name = "GenerateAllProductGroups",                    DisplayOrder = 60,                    Required = true,                    TxId = 60,                    Value = false                },
                new EntityProperty                {                    Id = 585,                    Name = "SiteStockTypeUID",                    DisplayOrder = 50,                    Required = false,                    TxId = 50,                    Value = new Guid("A92E52E8-C860-44A5-AAA8-A2DEA52E5DBF")                },
                new EntityProperty                {                    Id = 543,                    Name = "EnableDelayedPricing",                    DisplayOrder = 11,                    Required = false,                    TxId = 11,                    Value = false                },
                new EntityProperty                {                    Id = 542,                    Name = "DelayedPricingPeriod",                    DisplayOrder = 12,                    Required = true,                    TxId = 12,                    Value = 24                },
                new EntityProperty                {                    Id = 572,                    Name = "PNWebSubmitPriceRequest",                    DisplayOrder = 10,                    Required = false,                    TxId = 10,                    Value = false                },
                new EntityProperty                {                    Id = 538,                    Name = "DealerControl",                    DisplayOrder = 1,                    Required = false,                    TxId = 1,                    Value = false                },
                new EntityProperty                {                    Id = 539,                    Name = "DealerControlExport",                    DisplayOrder = 2,                    Required = false,                    TxId = 2,                    Value = false                },
                new EntityProperty                {                    Id = 540,                    Name = "DealerTrustCategoryUID",                    DisplayOrder = 1,                    Required = false,                    TxId = 1,                },
                new EntityProperty                {                    Id = 565,                    Name = "MappingLabel",                    DisplayOrder = 503,                    Required = false,                    TxId = 503,                },
                new EntityProperty                {                    Id = 579,                    Name = "RecodeSales",                    DisplayOrder = 504,                    Required = false,                    TxId = 504,                    Value = false                },
                new EntityProperty                {                    Id = 566,                    Name = "Motorway",                    DisplayOrder = 505,                    Required = false,                    TxId = 505,                    Value = false                },
                new EntityProperty                {                    Id = 541,                    Name = "DefinedOffsetCompetitorUID",                    DisplayOrder = 2,                    Required = false,                    TxId = 2,                },
                new EntityProperty                {                    Id = 576,                    Name = "PricingStrategy",                    DisplayOrder = 10,                    Required = false,                    TxId = 10,                },
                new EntityProperty                {                    Id = 583,                    Name = "SignType",                    DisplayOrder = 910,                    Required = false,                    TxId = 910,                },
                new EntityProperty                {                    Id = 586,                    Name = "SiteSystemActive",                    DisplayOrder = 99,                    Required = true,                    TxId = 99,                    Value = false                },
                new EntityProperty                {                    Id = 575,                    Name = "PriceIncreaseSetupDelay",                    DisplayOrder = 10,                    Required = true,                    TxId = 10,                    Value = 0                },
                new EntityProperty                {                    Id = 574,                    Name = "PriceDecreaseSetupDelay",                    DisplayOrder = 20,                    Required = true,                    TxId = 20,                    Value = 0                },
                new EntityProperty                {                    Id = 588,                    Name = "SysCommsDelay",                    DisplayOrder = 30,                    Required = true,                    TxId = 30,                    Value = 0                },
                new EntityProperty                {                    Id = 584,                    Name = "SiteOperational",                    DisplayOrder = 120,                    Required = true,                    TxId = 120,                    Value = false                },
                new EntityProperty                {                    Id = 544,                    Name = "ExportProperty",                    DisplayOrder = 80,                    Required = false,                    TxId = 80,                },
                new EntityProperty                {                    Id = 530,                    Name = "AlwaysWait",                    DisplayOrder = 501,                    Required = true,                    TxId = 501,                    Value = false                },
                new EntityProperty                {                    Id = 596,                    Name = "Volatility",                    DisplayOrder = 130,                    Required = false,                    TxId = 130,                },
                new EntityProperty                {                    Id = 551,                    Name = "GeneratePricesOnCostImport",                    DisplayOrder = 510,                    Required = true,                    TxId = 510,                    Value = false                },
                new EntityProperty                {                    Id = 808,                    Name = "ExportMinutesPastTheHourSwitch",                    DisplayOrder = 90,                    Required = true,                    TxId = 90,                    Value = false                },
                new EntityProperty                {                    Id = 807,                    Name = "ExportMinutesPastTheHour",                    DisplayOrder = 100,                    Required = true,                    TxId = 100,                    Value = 0                }
            };

            return propertyCollection;
        }
    }
}
